/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:85c4bd91-e76e-4374-bef3-eb5e8b61a1fd",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_I0vadhOx8",
    "aws_user_pools_web_client_id": "55kf4j10j4s96hi8urm7oetneh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dkattinptbdxbbr4k37ga7c64u.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-23eaonnlwff53fcxjmaflk4bb4"
};


export default awsmobile;
